#!/bin/sh
# $1 = kernel
# $2 = source me file
# $3 = skip module
# $4 = if null is a standard compile else contains a .config

KERNEL=$1
SOURCEMEFILE=$2
SKIP_MODULE_BUILD=$3
DEFCONFIG=$4

cd /Devel/NOVAsdk/Utils/rock
. ../functions.sh
clear_resfile

cleanup_and_configure() {
        make mrproper
        make distclean
        echo "Config is ${CONFIG_FILE}"
        make ${DEFCONFIG}
}

echo "Working on ${KERNEL} with ${SOURCEMEFILE}"
. ../${SOURCEMEFILE}
cd ../../Kernels/${KERNEL}
! [ -z "${DEFCONFIG}" ] && cleanup_and_configure
[ -d .git ] && mv .git gitb.git
make -j32
exit_if_error $? "make -j32"
if ! [ "${SKIP_MODULE_BUILD}"="skip_module" ]; then
        make -j32 modules
        exit_if_error $? "make -j32 modules"
else
        exit_if_error 0 "skipped modules compile"
fi
make rockchip/rk3328-novasomm7.dtb
exit_if_error $? "make dtb"
mv gitb.git .git
cd ../../Deploy
rm m7_Image m7_dtb.dtb m7.kernel.config
ln -s ../Kernels/${KERNEL}/arch/arm64/boot/Image m7_Image
ln -s ../Kernels/${KERNEL}/.config m7.kernel.config
ln -s ../Kernels/${KERNEL}/arch/arm64/boot/dts/rockchip/rk3328-novasomm7.dtb m7_dtb.dtb
exit_ok
