#!/bin/sh
# $1 = kernel
# $2 = source me file
# $3 = skip module
# $4 = if null is a standard compile else contains a .config


cd /Devel/NOVAsdk/Utils/rock
. ../functions.sh

KERNEL=$1
SOURCEMEFILE=$2
SKIP_MODULE_BUILD=$3
DEFCONFIG=$4

cleanup_and_configure() {
        make mrproper
        make distclean
        echo "Config is ${CONFIG_FILE}"
	make ${DEFCONFIG}
}

echo "Working on ${KERNEL} with ${SOURCEMEFILE}"
. ../${SOURCEMEFILE}
cd ../../Kernels/${KERNEL}
! [ -z "${DEFCONFIG}" ] && cleanup_and_configure
! [ -f .config ] && cleanup_and_configure
[ -d .git ] && mv .git gitb.git
make -j32
exit_if_error $? "make -j32"
if ! [ "${SKIP_MODULE_BUILD}"="skip_module" ]; then
        make -j32 modules
        exit_if_error $? "make -j32 modules"
else
        exit_if_error 0 "skipped modules compile"
fi
make rockchip/rk3399-novasom-m9.dtb
exit_if_error $? "make dtb"
mv gitb.git .git
cd ../../Deploy
rm m9_Image m9_dtb.dtb m9.kernel.config
ln -s ../Kernels/${KERNEL}/arch/arm64/boot/Image m9_Image
ln -s ../Kernels/${KERNEL}/.config m9.kernel.config
ln -s ../Kernels/${KERNEL}/arch/arm64/boot/dts/rockchip/rk3399-novasom-m9.dtb m9_dtb.dtb
exit_ok

