#!/bin/sh
# ${1} is file system name
# ${2} is the REFERENCE_SERVER IP
# ${3} is the KERNEL
# ${4} is the BOARD

PREPEND_PATH="/Devel/NOVAsdk/FileSystems"
DEPLOY_PATH="/Devel/NOVAsdk/Deploy"
FSNAME=$1
IP=$2
KERNEL=$3

HERE="/Devel/NOVAsdk/Utils/rock"
. ${HERE}/../functions.sh

if [ -z $4 ]; then
	BOARD="M7"
else
	BOARD=$4
fi
KERNEL_PATH="/Devel/NOVAsdk/Kernels/${KERNEL}"
FILESYSTEM_PATH="${PREPEND_PATH=}/${FSNAME}"
echo ""
echo "File system Name : $1"
echo "Assigned IP      : $2"
echo "Kernel           : $3"
cd ${PREPEND_PATH}/${FSNAME}
cp -a ../../Utils/FsBsp/novasis/NOVAsom${BOARD} board/novasis/.
echo "REFERENCE_SERVER=${2}" > board/novasis/NOVAsom${BOARD}/overlay/etc/sysconfig/system_vars
rm -f output/images/uInitrd

# here a double make is needed, the first to create the directories and the second after the modules installation
make
exit_if_error $? "make with no fs compiled"
if [ -f ${KERNEL_PATH}/arch/arm64/boot/Image ]; then
	cd ${HERE}
	./modules_install ${KERNEL_PATH}  ${FILESYSTEM_PATH} SourceMe64
	exit_if_error $? "modules_install with no fs compiled"
	cd ${PREPEND_PATH}/${FSNAME}
	make
	exit_if_error $? "make after modules_install with no file system"
fi
rm ${DEPLOY_PATH}/*.buildroot.config
cp ${PREPEND_PATH}/${FSNAME}/.config ${DEPLOY_PATH}/${FSNAME}.buildroot.config

exit_ok
