#!/bin/sh
cd /Devel/NOVAsdk/Utils/rock
. ../SourceMe32
. ../SourceMe64
. ../functions.sh

clear_resfile
rm -f ../../Deploy/m9-idbloader.img ../../Deploy/m9-uboot.img ../../Deploy/m9-trust.img
ATF_M9="/Devel/NOVAsdk/Bootloaders/atf2.3_m9"
TRUST_M9="/Devel/NOVAsdk/Bootloaders/rkbin_m9"
BOOT_M9="/Devel/NOVAsdk/Bootloaders/${1}"

cd ${ATF_M9}
M0_CROSS_COMPILE=arm-buildroot-linux-gnueabihf- make realclean
exit_if_error $? "make realclean"
M0_CROSS_COMPILE=arm-buildroot-linux-gnueabihf- make PLAT=rk3399
exit_if_error $? "make PLAT=rk3399"

cd ${TRUST_M9}
./tools/trust_merger RKTRUST/RK3399TRUST.ini
exit_if_error $? "trust_merger"

cd ${BOOT_M9}
export PATH=$PATH:${BOOT_M9}/scripts/dtc
export BL31=${ATF_M9}/build/rk3399/release/bl31/bl31.elf
make distclean  
exit_if_error $? "make distclean"

cp ${TRUST_M9}/trust.img .
make novasom-m9-rk3399_defconfig ; make -j32 ; make -j32 u-boot.itb
exit_if_error $? "make -j32 ; make -j32 u-boot.itb"
tools/mkimage -n rk3399 -T rksd -d tpl/u-boot-tpl.bin idbloader.img
ERR=$?
exit_if_error $ERR "mkimage"
cat spl/u-boot-spl.bin >> idbloader.img
exit_ok
