#!/bin/sh
. ./version

HERE="/Devel/NOVAsdk/Utils"
. ${HERE}/functions.sh
clear_resfile

cd /Devel/NOVAsdk/Kernels
echo -n "Looking for $1 on Novasom Industries github ..."
curl -s https://api.github.com/repos/Novasomindustries/${1}_${VERSION} > present
cat present | grep message
[ "$?" = "0" ] && exit_if_error 1 "Not found"
echo "Found!"
rm -rf ${1}_${VERSION} ${1}
git clone https://github.com/NovasomIndustries/${1}_${VERSION}.git
cd /Devel/NOVAsdk${VERSION}/Kernels
rm -f ${1}
ln -s ${1}_${VERSION} ${1}
exit_ok
