#!/bin/sh
cp /Devel/NOVAsdk/Utils/update_components_in_tmp /tmp/.
cp /Devel/NOVAsdk/Utils/version /tmp/.
chmod +x /tmp/update_components_in_tmp
/tmp/update_components_in_tmp
rm /tmp/update_components_in_tmp
