#!/bin/sh
# $1 = kernel
# $2 = source me file
. ../version
. ../functions.sh
clear_resfile

KERNEL=$1
SOURCEMEFILE=$2
echo "Working on ${KERNEL} with ${SOURCEMEFILE}"
. ../${SOURCEMEFILE}
cd ../../Kernels/${KERNEL}
make -j32 Image
exit_if_error $? "make -j32 Image"
make -j32 modules
exit_if_error $? "make -j32 modules"
make qcom/apq8016-sbc.dtb
cd ../../Deploy
rm Image
ln -s ../Kernels/${KERNEL}/arch/arm64/boot/Image
exit_ok
