#!/bin/sh
# ${1} is number of user partition
# ${2} is size of first user partition, if enabled
# ${3} is size of second user partition, if enabled
# ${4} is the device
# ${5} is the dtb
# ${6} is the NOVAsomParams file
# ${7} is the ramdisk size
# ./Uflash - 0 0 /dev/sdb"

. ./functions
. ../version
. ../functions.sh
clear_resfile

KERNEL="/Devel/NOVAsdk${VERSION}/Kernels/linux-imx_4.1.43/arch/arm/boot/zImage"
BOOTLOADER="/Devel/NOVAsdk${VERSION}/Bootloaders/u-boot-novasomU-2016.03"
UINITRD="/Devel/NOVAsdk${VERSION}/Deploy/uInitrd"
UBOOT_IMX="${BOOTLOADER}/u-boot.imx"
DISK=${4}
DTB="/Devel/NOVAsdk${VERSION}/DtbUserWorkArea/${5}.dtb"
NOVASOMPARAMS="/Devel/NOVAsdk${VERSION}/Utils/BootParameters/$6"
DEPLOY_DIR="/Devel/NOVAsdk${VERSION}/Deploy"
RAMDISK_SIZE="$7"

FILES="$UBOOT_IMX $KERNEL $DTB $UINITRD $NOVASOMPARAMS"
for i in ${FILES}; do
        if ! [ -f ${i} ]; then
                echo "File ${i} not found"
                exit
        fi
done

if [ ! -b ${DISK} ]; then
	echo "${DISK} not found"
	exit
fi
sudo umount ${DISK}* >/dev/null 2>&1
echo "Writing NOVAsomU uSD"
sleep 1
sudo echo -n "Writing u-boot ... "
sudo dd if=/dev/zero of=${DISK} bs=4M count=1; sync
sudo dd if=${UBOOT_IMX} of=${DISK} bs=512 seek=2; sync
sync

format_usd ${1} ${2} ${3} ${DISK}

sleep 1
echo y | sudo mkfs.vfat -F 16 ${DISK}1 -n BOOT 
exit_if_error $? "mkfs.vfat on ${DISK}1 with error $?"

echo y | sudo mkfs.ext3 -t ext3 -L U6Config ${DISK}3
exit_if_error $? "mkfs.vfat on ${DISK}3 with error $?"

if [ "${1}" = "1" ]; then
	echo y | sudo sudo mkfs.ext3 -t ext3 -L U6user1 ${DISK}2
	exit_if_error $? "mkfs.vfat on ${DISK}2 with error $?"
fi

if [ "${1}" = "2" ]; then
	echo y | sudo sudo mkfs.ext3 -t ext3 -L U6user1 ${DISK}2
	exit_if_error $? "mkfs.vfat on ${DISK}2 with error $?"
	echo y | sudo mkfs.ext3 -t ext3 -L U6user2 ${DISK}4
	exit_if_error $? "mkfs.vfat on ${DISK}4 with error $?"
fi

sync
sudo umount tmpmount >/dev/null 2>&1
rm -rf tmpmount
mkdir tmpmount
sleep 1
sudo mount ${DISK}1 tmpmount
[ "$?" != "0" ] && exit
sudo rm -rf tmpmount/*
[ "$?" != "0" ] && exit
echo `pwd`
echo -n "Copying novasomu.dtb ..."
sudo cp ${DTB} tmpmount/novasomu.dtb
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying u-boot files ..."
sudo cp ${UBOOT_IMX} tmpmount/.
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying zImage ..."
sudo cp ${KERNEL} tmpmount/zImage
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying uInitrd ..."
sudo cp ${UINITRD} tmpmount/.
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying `basename ${NOVASOMPARAMS}` ..."
echo "setramsize=setenv rdsize ${RAMDISK_SIZE}" > ${DEPLOY_DIR}/NOVAsomParams
cat ${NOVASOMPARAMS} >> ${DEPLOY_DIR}/NOVAsomParams
sudo cp ${DEPLOY_DIR}/NOVAsomParams tmpmount/NOVAsomParams
[ "$?" != "0" ] && exit

sudo umount tmpmount
sync
sudo umount ${DISK}
sync

exit_ok
