#!/bin/sh
. ../SourceMe32
. ../version
. ../functions.sh
clear_resfile
cd /Devel/NOVAsdk/Bootloaders/${1}
mv .git gitb
make distclean
exit_if_error $? "make distclean"
make mrproper
exit_if_error $? "make mrproper"
make novasomp_defconfig
exit_if_error $? "make novasomp_defconfig"
make -j32
exit_if_error $? "make -j32"
mv gitb .git
cd /Devel/NOVAsdk/Deploy
rm -f u-boot.img SPL
ln -s ${BOOT_P}/u-boot.img
ln -s ${BOOT_P}/SPL
exit_ok
