#!/bin/sh
. ../SourceMe32
. ../version
. ../functions.sh
clear_resfile

cd /Devel/NOVAsdk/Bootloaders/${1}
make distclean
exit_if_error $? "make distclean"
make mrproper
exit_if_error $? "make mrproper"
make novasomu_defconfig
exit_if_error $? "make novasomu_defconfig"
make -j32
exit_if_error $? "make -j32"
exit_ok

