#!/bin/sh
. ../SourceMe32
. ../version
. ../functions.sh
clear_resfile
BOOT_P="../../Bootloaders/u-boot-novasomP-2015.04"
cd ${BOOT_P}
make distclean
[ "$?" != "0" ] && exit
make mrproper
[ "$?" != "0" ] && exit
make novasomp_defconfig
[ "$?" != "0" ] && exit
make -j32
[ "$?" != "0" ] && exit
cd /Devel/NOVAsdk${VERSION}/Deploy
rm -f u-boot.img SPL
ln -s ${BOOT_P}/u-boot.img
ln -s ${BOOT_P}/SPL
exit_ok
